### ISSUE TITLE
Insufficient Permissions

### ISSUE THREAD

**Issue by thecodingwizard** [api-ai/api-ai-android-sdk#10]
With the standard two INTERNET and RECORD_AUDIO permissions, it throws an Insufficient Permissions error. You must add the ACCESS_NETWORK_STATE permission for it to work.

**Comment by xVir** [comment]
Hi, @theCodingWizard,
Do you have any problems with permissions in your app?
In our sample app we have the following permissions ([AndroidManifest](https://github.com/api-ai/api-ai-android-sdk/blob/master/apiAISampleApp/src/main/AndroidManifest.xml)):
```xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
   
<!-- this permission for dev purposes only -->
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
   
<!-- this permissions for Bluetooth support -->
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BROADCAST_STICKY" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
```

So, we use only two permissions.

Could you please check if our SDK sample app works on your device?

Thanks.
