### ISSUE TITLE
NetworkOnMainThreadException

### ISSUE THREAD

**Issue by Florent1510** [api-ai/api-ai-android-sdk#12]
Hey!

When trying to do what the tutorial says in the own application, I get a NetworkOnMainThreadException. How can I fix it? Already tried working with a Thread but that didn't work.

**Comment by xVir** [comment]
Hi, @Florent1510, 
could you please post the full stack trace of the exception here.
Thanks.

**Comment by xVir** [comment]
It seems, problem resolved
