### ISSUE TITLE
Crash doing voice recognition

### ISSUE THREAD

**Issue by yultide** [api-ai/api-ai-android-sdk#13]
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime: Process: com.getscarlett.android, PID: 8094
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:304)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:  Caused by: java.lang.NullPointerException: lock == null
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.io.Reader.<init>(Reader.java:64)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.io.InputStreamReader.<init>(InputStreamReader.java:120)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at org.apache.commons.io.IOUtils.copy(IOUtils.java:1906)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at org.apache.commons.io.IOUtils.toString(IOUtils.java:778)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at ai.api.AIDataService.doTextRequest(AIDataService.java:319)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at ai.api.AIDataService.doTextRequest(AIDataService.java:282)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at ai.api.AIDataService.request(AIDataService.java:107)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at ai.api.services.GoogleRecognitionServiceImpl$1.doInBackground(GoogleRecognitionServiceImpl.java:146)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at ai.api.services.GoogleRecognitionServiceImpl$1.doInBackground(GoogleRecognitionServiceImpl.java:138)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
11-24 15:17:47.267 8094-8877/com.getscarlett.android E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)

**Comment by xVir** [comment]
Hi, @yultide ,
Could you please add code you use to call API.AI service?
Thanks!

**Comment by yultide** [comment]
Hi @xVir,

I just used a simple AIButton element and registered a callback to it.  I tried on another device and AIButton works just fine.  I don't know if it's a phone specific thing.  The one having problems is a Nexus 4 w/ Android 5.1.1.  The one that works is HTC One w/ 5.1.1.

The Nexus 4 seems to get stuck in here all the time.

https://github.com/api-ai/api-ai-android-sdk/blob/master/ailib/src/main/java/ai/api/AIDataService.java#L306

**Comment by xVir** [comment]
It seems it could not connect to our server... Could you please try to install and check this test application? https://www.dropbox.com/s/a0nnbtlcufk8qs1/apiAISampleApp-debug.apk?dl=0
Thanks!

**Comment by yultide** [comment]
More information for you.  It seems to be a specific wifi network at the office I'm at.  When I'm at home, my app and the sample app works just fine, but my app and the sample app also dies using the work wifi with the same error.  

I had to spam clicking the button and sending voice constantly to get it to break.  You're welcome to close the bug, but maybe there's a way to capture the exception and call onError() on the listener.  Thanks for the help.

**Comment by xVir** [comment]
Hi, @yultide! 
Thanks for information!
I will add processing for this exception.
Thanks!

**Comment by xVir** [comment]
Fixed with https://github.com/api-ai/api-ai-android-sdk/blob/3acab9a33fa780e4488ef49f20b68c7e0e057b5a/ailib/src/main/java/ai/api/AIDataService.java#L362
