### ISSUE TITLE
problem in voice recogonization

### ISSUE THREAD

**Issue by sarathi1989** [api-ai/api-ai-android-sdk#14]
I speak some local address but it should not detect properly.

**Comment by xVir** [comment]
Hi, @sarathi1989, do you use Speaktoit or System recognition engine?
Thanks!

**Comment by xVir** [comment]
Also, some addresses can't be recognized, because of recognition engine must be trained for specific words.

**Comment by sarathi1989** [comment]
I am using System recognition engine

**Comment by sarathi1989** [comment]
final AIConfiguration config = new AIConfiguration(CLIENT_ACCESS_TOKEN,
                SUBSCRIPTION_KEY, AIConfiguration.SupportedLanguages.English,
                AIConfiguration.RecognitionEngine.System);

        aiService = AIService.getService(this, config);
        aiService.setListener(this);

**Comment by xVir** [comment]
It uses Google recognition. So, please check if **Google Search** recognize your speaking.

**Comment by sarathi1989** [comment]
how to check google search plz help me!

**Comment by xVir** [comment]
@sarathi1989 please try something like in the video https://youtu.be/jgzhyVjCtRw

**Comment by sarathi1989** [comment]
if we change anything in GoogleRecognitionServiceImpl.class to avoid this problem?

**Comment by sarathi1989** [comment]
it is possible then plz tell me the process

**Comment by xVir** [comment]
@sarathi1989 no, Google Recognition engine is managed by Google and does not have options for fine tuning...
