### ISSUE TITLE
Disable Google SpeechRecognizer beep sound

### ISSUE THREAD

**Issue by xVir** [api-ai/api-ai-android-sdk#2]
Add option to the AIConfiguration to disable beep sound for speech recognition process

**Comment by nsp4real** [comment]
and how do you activate this add disable thing?


*Contact me by cell @ (509)981-3513 or email me at **   nsp4real@gmail.com
<nsp4real@gmail.com>*

**Comment by nsp4real** [comment]
additionally my Biggest Issue with my AI API assistant is her lack of
ability to Correctly or usefully respond to commands,searches & --questions
that include Kuss  words, inappropriate manners or topics of adults levels
, I not a child and want a assistant like real life ability to have any
level of appropriate or not appropriate  relationship, understanding of
personalization and to basically do what ever I ask of her. including CUSS
words and XXX affiliated commands, searches and questions. all she does if
the same use of a small set of bullshit responses that are getting on my
nerves and piss me off that she wont do as told or learn topics of this
nature?

 To sum up my request : " I' m a inappropriate type person (she should have
ability to be inappropriate as well) i need an assistant that can learn to
adapt to my nature and not be a cocky bitch about it and ignore the subject
I spoke at hand.

**Is there something you  can do to remedy this issue so she is what i
purchased her life long subscription that stated you can abilities to learn
from you over time (my understanding is that is not at first knows what or
how to react on commands, questions & searches, that she would eventually
or you would fix it through requests, is this not true ?)

I appreciate the assistance and help, thank you

Noah Patton 509-981-3513
nsp4real@gmail.com



*Contact me by cell @ (509)981-3513 or email me at **   nsp4real@gmail.com
<nsp4real@gmail.com>*

**Comment by MrHug** [comment]
Is there any progress on this by any chance? I've looked at it for a similar application in the past, but never managed to do this properly...

**Comment by xVir** [comment]
Hi, @MrHug 
Now if you use Speaktoit recognition you can set up the start and stop listening sounds:
```java
config.setRecognizerStartSound(getResources().openRawResourceFd(R.raw.test_start));
config.setRecognizerStopSound(getResources().openRawResourceFd(R.raw.test_stop));
config.setRecognizerCancelSound(getResources().openRawResourceFd(R.raw.test_cancel));
```

But Google Recognizer does not support this feature.

**Comment by MrHug** [comment]
Hi @xVir,

Thanks for your response, I will defintely look into this :)

Gr. Stefan

**Comment by xVir** [comment]
You are Welcome,
Thanks
