### ISSUE TITLE
Quick replies json not getting in AiResponse Object

### ISSUE THREAD

**Issue by changulpaye** [api-ai/api-ai-android-sdk#21]
I am not getting quick replies JSON Array in AiResponse Object.

**Comment by xVir** [comment]
Hi, @changulpaye 
Sorry, this functionality is under development now. It should be ended until end of the week.

Thanks.

**Comment by changulpaye** [comment]
Thank you so much for quick reply :+1:

**Comment by folomeev** [comment]
The fix is currently available in "javasdk-migration" branch. In the nearest future it is going to be merged into the master branch.

**Comment by xVir** [comment]
Hi, @changulpaye 
This should work now in library version 2.0.1, please check.

Thanks!

**Comment by nuriaruiz** [comment]
For me is not working yet.
