### ISSUE TITLE
How to used UTF-16. I want to used in Hindi Language

### ISSUE THREAD

**Issue by skbhati199** [api-ai/api-ai-android-sdk#24]
Please help me. How can I do utf-16 in api.ai for hindi language support

**Comment by xVir** [comment]
Hi, @skbhati199 
Sorry, Hindi now is not supported by api.ai https://docs.api.ai/docs/languages
Or you just want to use agent in another language with Hindi parts? 

Thanks!

**Comment by coderoda** [comment]
it says it supports in the documentation

**Comment by coderoda** [comment]
Hi the documentation of Dialogflow says it supports Hindi
