### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by LuYongJin** [api-ai/api-ai-android-sdk#25]
支持的最低版本是多少(zhi chi de zui di ban ben shi duo shao)

**Comment by xVir** [comment]
Hi, @LuYongJin 
Formally, the library should work on Android 2.2 (sdk version 8) https://github.com/api-ai/api-ai-android-sdk/blob/master/gradle.properties#L39

But it will be better to use Android 4.4 (19) and above.

Thanks!
