### ISSUE TITLE
Use of StandardCharsets.UTF_8 in AIDataService breaks compatibility with Android SDK prior to 19

### ISSUE THREAD

**Issue by DiegoAnfuso** [api-ai/api-ai-android-sdk#26]
The use of SDK 19+ constant StandardCharsets.UTF_8 crash the service in devices prior to Android SDK 19.

Error:
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets at ai.api.AIDataService.<clinit>(AIDataService.java:59)

**Comment by folomeev** [comment]
Fixed the issue in Java SDK, it will be available in a closest release.

**Comment by xVir** [comment]
Hi, @DiegoAnfuso 
Could you please try library version 2.0.2:
```
compile 'ai.api:sdk:2.0.2@aar'
```

The problem should be fixed now.

Thanks!

**Comment by DiegoAnfuso** [comment]
Hi, the problem was solved upgrading this:

`compile 'ai.api:libai:1.3.5'`

Thanks for the quick feedback!
