### ISSUE TITLE
Language default when not in "SupportedLanguages"

### ISSUE THREAD

**Issue by SolidTerre** [api-ai/api-ai-android-sdk#31]
Hi,

I'm using the Android SDK, building a simple test app to know if I'm going to use your services or another :-)

When I try this:
`final AIConfiguration.SupportedLanguages lang = AIConfiguration.SupportedLanguages.fromLanguageTag("nl");`

The "lang" is always English. How come it doesn't support Dutch when your doc says it does (https://docs.api.ai/docs/languages)? Did I miss something?

Thank you !

**Comment by xVir** [comment]
Hi @SolidTerre,
Please try the new versions:
```
compile 'ai.api:libai:1.4.8'
compile 'ai.api:sdk:2.0.5@aar'
```

Thanks!
