### ISSUE TITLE
Getting Compiler error 

### ISSUE THREAD

**Issue by sudheepsnair** [api-ai/api-ai-android-sdk#9]
ai.api.util.BluetoothController file is missing

**Comment by xVir** [comment]
Hi, @sudheepsnair !
This problem is due to the new version of the library that has not yet been published.
Today library will be published

also you can change settings in the `apiAISampleApp/build.gradle` 

```groovy
//compile 'ai.api:sdk:1.6.1@aar'
compile project(':ailib')
```
